from typing import Annotated

from numpy.typing import ArrayLike


def pack(x: Annotated[ArrayLike, dict(dtype='uint8', order='C')], nbits: int, bitorder: str = 'big', parallel: bool = False) -> Annotated[ArrayLike, dict(dtype='uint8', order='C')]: ...

def readbestprof(arg: str, /) -> tuple: ...

def readdat(arg: str, /) -> tuple[dict, Annotated[ArrayLike, dict(dtype='float32', shape=(None))]]: ...

def readfft(arg: str, /) -> tuple[dict, Annotated[ArrayLike, dict(dtype='float32', shape=(None))]]: ...

def readfil(arg: str, /) -> tuple[dict, Annotated[ArrayLike, dict(shape=(None, None))]]: ...

def readhdr(arg: str, /) -> dict: ...

def readinf(arg: str, /) -> dict: ...

def readpfd(arg: str, /) -> dict: ...

def readpolycos(arg: str, /) -> list: ...

def readtim(arg: str, /) -> tuple[dict, Annotated[ArrayLike, dict(shape=(None))]]: ...

def unpack(x: Annotated[ArrayLike, dict(dtype='uint8', order='C')], nbits: int, bitorder: str = 'big', parallel: bool = False) -> Annotated[ArrayLike, dict(dtype='uint8', order='C')]: ...

def writebestprof(arg0: dict, arg1: Annotated[ArrayLike, dict(dtype='float64', shape=(None))], arg2: str, /) -> None: ...

def writedat(arg0: dict, arg1: Annotated[ArrayLike, dict(dtype='float32', shape=(None))], arg2: str, /) -> None: ...

def writefft(arg0: dict, arg1: Annotated[ArrayLike, dict(dtype='float32', shape=(None))], arg2: str, /) -> None: ...

def writefil(arg0: dict, arg1: Annotated[ArrayLike, dict(dtype='float32', shape=(None, None))], arg2: str, /) -> None: ...

def writehdr(arg0: dict, arg1: str, /) -> None: ...

def writeinf(arg0: dict, arg1: str, /) -> None: ...

def writepfd(arg0: dict, arg1: str, /) -> None: ...

def writepolycos(arg0: list, arg1: str, /) -> None: ...

def writetim(arg0: dict, arg1: Annotated[ArrayLike, dict(dtype='float32', shape=(None))], arg2: str, /) -> None: ...
