name: Build and upload priwo to PyPI.

on:
  release:
    types:
      - published

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # Build sdist and wheels.
  dist:
    name: Build sdist and wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Build sdist and wheels.
        run: pipx run build
      - name: Check metadata
        run: pipx run twine check dist/*
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: dist/*

  # Upload the wheels and source distribution to PyPI.
  publish:
    needs: [dist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          password: ${{ secrets.pypi_password }}
