name: Testing priwo!

on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1
    - name: Set up Python ${{ matrix.python-version }}.
      uses: actions/setup-python@v4
      with:
          python-version: ${{ matrix.python-version }}
    - name: Display Python version.
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ward
        pip install -e .
    - name: Run tests for priwo.
      run: just test
